### ISSUE TITLE
taboo 버튼 누를 시 에러

### ISSUE THREAD

**Issue by dobeeisfree** [sejinq/HelloStranger#14]
누르지 못하게하거나
(타부 옆에 온오프 스위치가 있으므로)

누르면 타부셋팅 액티비티로 넘어가야함.

지금은 `activity_main_drawer.xml`에서  item에 `android:enabled="false"`로 처리로 해둠

**Comment by dobeeisfree** [comment]
```
10-20 22:54:51.247 9393-9393/com.example.secpc.hellostranger W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.Class.newInstance()' on a null object reference
10-20 22:54:51.247 9393-9393/com.example.secpc.hellostranger W/System.err:     at com.example.secpc.hellostranger.activity.MainActivity.onNavigationItemSelected(MainActivity.java:114)
10-20 22:54:51.247 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:153)
10-20 22:54:51.247 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
10-20 22:54:51.247 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:85)
10-20 22:54:51.247 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
10-20 22:54:51.247 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
10-20 22:54:51.247 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:328)
10-20 22:54:51.247 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.view.View.performClick(View.java:5609)
10-20 22:54:51.248 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.view.View$PerformClick.run(View.java:22259)
10-20 22:54:51.248 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
10-20 22:54:51.248 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-20 22:54:51.248 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.os.Looper.loop(Looper.java:154)
10-20 22:54:51.248 9393-9393/com.example.secpc.hellostranger W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
10-20 22:54:51.248 9393-9393/com.example.secpc.hellostranger W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-20 22:54:51.248 9393-9393/com.example.secpc.hellostranger W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
10-20 22:54:51.248 9393-9393/com.example.secpc.hellostranger W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
10-20 22:54:51.248 9393-9393/com.example.secpc.hellostranger D/AndroidRuntime: Shutting down VM
10-20 22:54:51.250 9393-9393/com.example.secpc.hellostranger E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.example.secpc.hellostranger, PID: 9393
                                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                                   at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:431)
                                                                                   at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:481)
                                                                                   at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:472)
                                                                                   at com.example.secpc.hellostranger.activity.MainActivity.onNavigationItemSelected(MainActivity.java:119)
                                                                                   at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:153)
                                                                                   at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
                                                                                   at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:85)
                                                                                   at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
                                                                                   at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:328)
                                                                                   at android.view.View.performClick(View.java:5609)
                                                                                   at android.view.View$PerformClick.run(View.java:22259)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

**Comment by sejinq** [comment]
fragment 생성 try-catch를 거치지 않게 바로 return ture;  코드로 함수 빠져나가 줌.
