### ISSUE TITLE
상단바 알파값으로 바뀐뒤 안됨

### ISSUE THREAD

**Issue by dobeeisfree** [sejinq/HelloStranger#22]
``` JAVA

10-29 21:12:22.446 25415-25415/com.example.secpc.hellostranger E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.example.secpc.hellostranger, PID: 25415
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.secpc.hellostranger/com.example.secpc.hellostranger.activity.OrderSheetActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
                                                                                     at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:145)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                                                  Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                                                                                     at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:557)
                                                                                     at android.app.Activity.onApplyThemeResource(Activity.java:3867)
                                                                                     at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
                                                                                     at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
                                                                                     at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:90)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767) 
                                                                                     at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:145) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5951) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by dobeeisfree** [comment]
http://stackoverflow.com/questions/29166809/5-1-crash-a-taskdescriptions-primary-color-should-be-opaque 
이렇게 바꿔주면 되는둣함
